services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.9.0
    container_name: kokoro
    restart: unless-stopped

    networks:
      - tts_internal

networks:
  tts_internal:
    external: true
